version: "3.8"
services: 
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: runner
    restart: always
    environment:
      - NODE_ENV=production
      - APP_BASE_PATH=${APP_BASE_PATH}
  backend:
    container_name: backend
    build:
      context: ./backend
      target: prod
    restart: always
    environment:
      - SCRIPT_NAME=${APP_BASE_PATH}
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    restart: always
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
      - APP_BASE_PATH=${APP_BASE_PATH}
    ports:
      - "127.0.0.1:8080:8080"
