version: "3.8"
services:
  frontend:
    build:
      target: dev
    command: npm run dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app:Z
      - /app/node_modules
      - /app/.next
  backend:
    build:
      target: dev
    volumes:
      - ./backend:/app:Z
    ports:
      - "127.0.0.1:5678:5678"
    command: python -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5678 -m gunicorn --access-logfile '-' --error-logfile '-' --log-level DEBUG --bind 0.0.0.0:5000 --reload wsgi:app -e ENV=development --timeout 0
