version: "3.8"
services: 
  frontend:
    build:
      target: dev
    command: npm run dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
      - ./frontend/.next:/app/.next
  backend:
    build:
      target: dev
    volumes:
      - ./backend:/app
    command: gunicorn --bind 0.0.0.0:5000 --reload wsgi:app
  # nginx:
  #   container_name: nginx
  #   build:
  #     context: ./nginx
  #   ports:
  #     - 8080:8080
