version: "3.8"
services: 
  frontend:
    build:
      target: dev
    command: npm run dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
  backend:
    build:
      target: dev
    volumes:
      - ./backend:/app
      - /app/cache
    command: gunicorn --access-logfile '-' --error-logfile '-' --log-level DEBUG --bind 0.0.0.0:5000 --reload wsgi:app -e ENV=development
